---
engines:
  duplication:
    enabled: true
    config:
      languages:
        - ruby
  fixme:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
    - "**.gemspec"
    - "**.rb"
exclude_paths:
  - "spec/"
