require:
  - rubocop-performance
  - rubocop-rspec

Layout/AlignHash:
  Exclude:
    - svgeez.gemspec

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - svgeez.gemspec

Metrics/LineLength:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 2

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolArray:
  Enabled: false
