require:
  - rubocop-performance
  - rubocop-rspec

Layout/HashAlignment:
  Exclude:
    - svgeez.gemspec

Layout/LineLength:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - svgeez.gemspec

Naming/RescuedExceptionsVariableName:
  PreferredName: exception

RSpec/MultipleExpectations:
  Max: 2

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolArray:
  Enabled: false
