require:
  - rubocop-performance
  - rubocop-rspec

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Metrics/LineLength:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/MessageSpies:
  EnforcedStyle: receive

RSpec/MultipleExpectations:
  Max: 2

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
